apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sarikapt9/my-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: supabase-postgres-secret
                  key: POSTGRES_DSN
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-postgres-secret
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-postgres-secret
                  key: SUPABASE_KEY
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002  # Exposes backend on NodePort
  type: NodePort  # Exposes backend outside cluster
