apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sarikapt9/my-frontend:latest
          ports:
            - containerPort: 8080  # Changed from 80 to 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80    
      targetPort: 80  # Changed from 8080 to 80 (matches NGINX)
      nodePort: 30001 
  type: NodePort  
